Revert "adb: add transport benchmark."
This reverts commit 5811b52a864b3342290f68be1db108b38dda90cb.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293